### ISSUE TITLE
Not responsive

### ISSUE THREAD

**Issue by Sambuca85** [webkul/hotelcommerce#1]
Sorry but theme it's not really responsive. I've try with http://www.responsinator.com/ and it's not responsive with all model. Why you don't have used bootstrap?

Hi.

**Comment by webkul** [comment]
Thanks Sambuca85 for raising issue . offcourse we are using bootstrap .Almost 90% of site is responsive , for rest  we are looking into responsiveness in detail . will soon fix that

**Comment by webkul** [comment]
We look into this problem in detail and found Responsive is only creating problem in 240 px width . please let me know if you are facing problem in other case too

**Comment by webkul** [comment]
Now Hotel commerce is completely Responsive
