### ISSUE TITLE
Error when installing marketplace module on my subdomain

### ISSUE THREAD

**Issue by donatienmigue** [webkul/hotelcommerce#100]
Have this error on the apache error log:
**AH00524: Handler for (null) returned invalid result code 70007,**
And have a 505-page error on my browser.

**Comment by sumitwebkul** [comment]
@migudonatien 

Please tell me your QloApps version.
Can you tell me on which page this error is occurring?
Also please mention the steps once to reproduce this error.

**Comment by donatienmigue** [comment]
QloApps version: 1.4.1
An error occurred on modules page
Just try to install the market place on your QloApps.

**Comment by shreesh-webkul** [comment]
@migudonatien 

please provide the link from where we can get the marketplace module.

**Comment by donatienmigue** [comment]
https://store.webkul.com/Qloapps-Marketplace.html

**Comment by shreesh-webkul** [comment]
@migudonatien 

Thanks for confirming the link.

Please create a ticket on the provided link as we provide support for our modules on our helpdesk.
https://webkul.uvdesk.com/en/customer/create-ticket/

we provide support for QloApps core issue on GitHub.

**Comment by donatienmigue** [comment]
Have installed on my dev environment and deploy the file on my production environment then the module appears into the module list. Please don't ask a professional company to send their FTP access it's not secure.
