### ISSUE TITLE
New next version?

### ISSUE THREAD

**Issue by wdammak** [webkul/hotelcommerce#101]
No new versions? the project is at a standstill?

**Comment by sumitwebkul** [comment]
@wdammak 
We are in the last phase of releasing the new version.
We have made many big changes in the new version.
So it is taking time in the release.
Please wait for some more time. It's in the way to release.
Thanks.

**Comment by morepixel** [comment]
Hi, do you have a time schedule, because we want to implement it for a customer. And if there is a new version coming soon, we should wait maybe...

**Comment by faizansari350** [comment]
Hi @morepixel 
We are on the verge of launching the next version. Please expect the launch by 31st August. 
And if anything comes out of the blue then also it will not pass the first week of September.

**Comment by faizansari-bd** [comment]
Hi, 
We are on the verge of launching our next version. Please expect it by 31st August. 
And if something comes out of the blue then also it will not take more than the first week of September.

**Comment by wdammak** [comment]
I hope the whole team is doing very well!

**Comment by faizansari-bd** [comment]
Hi @wdammak 
Yes, we are doing great and we hope for the same on your side. 
The new version is now released, please check it out. 

Hope you will like it!!!

**Comment by wdammak** [comment]
thx best team!
