### ISSUE TITLE
Room availability

### ISSUE THREAD

**Issue by morepixel** [webkul/hotelcommerce#102]
Hi, 

Is there a possibility for the seller to manage the availability data of his rooms inside the Marketplace Module?

Thank you in advance
Lars

**Comment by sumitwebkul** [comment]
@morepixel 
Yes, the seller can create his own Hotels, room types, and rooms from his account.
I recommend you to please go through the detailed blog of marketplace https://qloapps.com/qloapps-marketplace/.
So that you can know all the features of the marketplace.

If you have further doubts then please explain the query in more detail.

Thanks

**Comment by morepixel** [comment]
@sumitwebkul 
Thank you for your answer! I really appreciate it, that you take your time to answer those questions!

Yes i have seen that sellers can create their own Hotels room types, rooms etc. 
But what i have not seen, was if there is a posibility for the seller to manage the availability of his rooms...
Ideally there could be a calendar where the seller can manage the daily availabilites.
A lot of the sellers do sell their accommodations also directly, so they need to adjust that data on a daily or weekly basis.

Thank you
Lars

**Comment by faizansari-bd** [comment]
Hi @morepixel 
The default QloApps Marketplace system has a calendar in which we show some stats for the rooms on a particular date. But the calendar does not have the functionality of managing the availability of the rooms. We manage the room availability in the Room types tab separately. 
But if you want to have the availability management on the calendar then please we will need to discuss it so please raise a ticket at https://webkul.uvdesk.com/en/customer/create-ticket/

**Comment by morepixel** [comment]
Thank you, that should be enough. If not i will come back to you. 

One last question: My customer wants to sell additional activities. Such as a Bike-Tour or similar things...
Is there any chance to combine the room with some extra activities an sell them separately?

Regards
Lars

**Comment by shreesh-webkul** [comment]
Hi @morepixel 

You can sell extra activities along with rooms by using additional facilities feature. These facilities can be bought along with rooms as an addon. For detailed info on this feature please refer to blog (https://qloapps.com/qlo-reservation-system/#section-9)
