### ISSUE TITLE
Bug: Bad SQL query on demo->adminhtl

### ISSUE THREAD

**Issue by wdammak** [webkul/hotelcommerce#104]
Bad SQL query
Unknown column 'a.id' in 'field list'

https://demo.qloapps.com/adminhtl/index.php?controller=AdminOrderRefundRequests&token=b82deceb000fd13f608f5c28fe9e8bce

**Comment by sumitwebkul** [comment]
@wdammak
Thanks for reporting.
We have resolved it in demo.
