### ISSUE TITLE
Bug: Tab Additional Facilities on demo->adminhtl don't work

### ISSUE THREAD

**Issue by wdammak** [webkul/hotelcommerce#105]
Tab Additional Facilities in detail product page

https://demo.qloapps.com/adminhtl/index.php?controller=AdminProducts&id_product=3&updateproduct&token=fdaa59eab4139a9be9830e18a6046738

**Comment by sumitwebkul** [comment]
@wdammak
Thanks for reporting.
This issue was in demo.
Resolved.
