### ISSUE TITLE
V1.5.0 feedback png vs jpg

### ISSUE THREAD

**Issue by wdammak** [webkul/hotelcommerce#106]
I would like to congratulate you for the great work done! 
I have some feedback after going through the code and features of version v1.5.0:

Why did you switch from png to jpg !?
The jpg doesn't support transparency (nor animation)
Currently everyone in the process of switching from jpg&png to svg so that the icons are easily given a makeover to the themes and more beauty/quality to the appearance.

Anyway the png is better than the jpg for the icons especially!

**Comment by sumitwebkul** [comment]
@wdammak 

Thanks for your valuable feedback.
Actually, these changes are not related to moving toward png to jpg or other formats.
There are more than one formats were used in the system(jpg and png) and currently jpg is the system we are using saving for images. So to use one format we have made this change.
All the above points of yours are valuable and whenever we will in process of changing image formats, We we consider these points in roadmap.
Thanks
