### ISSUE TITLE
Bug: V1.5.0 payments configuration page

### ISSUE THREAD

**Issue by wdammak** [webkul/hotelcommerce#107]
https://demo.qloapps.com/adminhtl/index.php?controller=AdminPaymentsSetting&token=de73af6f1f288ff30490224c0b4cf777

**Comment by sumitwebkul** [comment]
@wdammak 

This page was built so that payment modules can show their payment configurations on this page.
Currently, no modules are there to show its configuration, That's why page is blank.

Thanks for reporting. We will improve this page in the next upgrade.
