### ISSUE TITLE
Communicate changes in the develop branch

### ISSUE THREAD

**Issue by wdammak** [webkul/hotelcommerce#114]
Since you are using git why not instantly communicate the changes made to the develop branch  (you validate the commits that you think are correct) and once it's stable announce the creation of a new release. 

This is the principle of github and the community! This will encourage developers and volunteers to contribute and react. The progress of the project will certainly take giant strides!

**Comment by faizansari-bd** [comment]
Hi,
Again thanks for the suggestion.
We have already implemented this workflow to take contributions to QloApps. As you can see in the screenshot that we have created a develop branch.
![webkul-hotelcommerce-at-develop](https://user-images.githubusercontent.com/54266810/94472134-ef5f3780-01e7-11eb-9a47-400154071296.png)

Now all the activities like improvements, bug resolving and adding features will be done on this branch only and then after testing it will be released on the main branch.
This will make contributions to QloApps very easy and ultimately this will help the community. And we also suggest you send all your pull requests on the develop branch only.

**Comment by wdammak** [comment]
@faizansari-bd thx! done all latest commits in develop branch
