### ISSUE TITLE
PHP 7.2 & 7.3 & 7.4

### ISSUE THREAD

**Issue by wdammak** [webkul/hotelcommerce#123]
I have communicated the modifications to make the application work with php 7.2 / 7.3 / 7.4 this will free up its use and increase security!
Please purge and give me feedback from the tests!
I have already performed tests on php 7.4.10 without any problem!

Please update  tools/tcpdf/tcpdf.php  by attached file

[tcpdf.zip](https://github.com/webkul/hotelcommerce/files/5293973/tcpdf.zip)

**Comment by faizansari-bd** [comment]
Hi, 
We are checking this, please allow us some time.

**Comment by sumitwebkul** [comment]
@wdammak 

Please create a PR regarding the changes. So that we can review it and use it on upgrade version.

Thanks.

**Comment by wdammak** [comment]
@sumitwebkul 
Hello, I have already done it, all my last commits are made to run the application on php7.4 / 7.3 / 7.2, moreover tested without any problem and the logs is empty after having almost browsed everywhere the application features.

Note my changes don't prevent the application from continuing to work on the old php version including the php5 version.
So thank you for already merging the commits and retesting on your part on php 7.4 and I will be at your disposal if there is a bug to fix.

Currently almost the majority of hosts have evolved into php7.3 and especially php7.4, so it's necessary to adopt it so as not to constrain users to look for another solution.

Thanks.

**Comment by sumitwebkul** [comment]
@wdammak 

If you have created PR then we will check them and merge it.

Regarding php7.4 / 7.3 / 7.2 versions compatibility, we are already concerned about it and definitely, we will make it compatible soon.

Thanks for the commitment you have shown towards QloApps. It is surely helping QloApps for its improvement.

Thanks & Regards.

**Comment by wdammak** [comment]
@sumitwebkul 
The objective of having a develop branch is to marge the commits more quickly in order to continue developing on them without worrying about possible bugs because it's precisely a development branch made to develop/test/fix after feedback.

**Comment by sumitwebkul** [comment]
@wdammak 

We appreciate your efforts. But in the develop branch also we will check the PR properly before merging it to the branch.

We are reviewing the PR and hope they will be processed soon.

Thanks

**Comment by wdammak** [comment]
no one wants to run it on php7 except me 0^0? the world has changed and we will soon switch to php8 and in a few months you will have problems finding a renowned host in php5

**Comment by sumitwebkul** [comment]
@wdammak 

We are also concerned about this. We also do not want our system to be outdated with the changing technologies used in the QloApps.
But We are working to update the whole system compatibility with the latest PHP versions. So we will check and merge PRs regarding the version update when we decide to release the version with updated compatibility with PHP versions.

Thanks

**Comment by loki-odinson** [comment]
Hi @webkul. Does the new release support php7?
