### ISSUE TITLE
id_hotel_button_chosen does not exist

### ISSUE THREAD

**Issue by wdammak** [webkul/hotelcommerce#1310]
https://github.com/Qloapps/QloApps/blob/950b37ed1c044f2252149aa09ca7f9adeb97991e/modules/wkroomsearchblock/views/js/wk-room-search-block.js#L1003C1-L1003C98

**Comment by shreesh-webkul** [comment]
The element `id_hotel_button_chosen` is auto generated when `chosen` plugin is initialized on the element `id_hotel_button`
https://github.com/Qloapps/QloApps/blob/950b37ed1c044f2252149aa09ca7f9adeb97991e/modules/wkroomsearchblock/views/js/wk-room-search-block.js#L158

**Comment by wdammak** [comment]
> The element `id_hotel_button_chosen` is auto generated when `chosen` plugin is initialized on the element `id_hotel_button`
> 
> https://github.com/Qloapps/QloApps/blob/950b37ed1c044f2252149aa09ca7f9adeb97991e/modules/wkroomsearchblock/views/js/wk-room-search-block.js#L158

Thanks!
