### ISSUE TITLE
Feature Request: Customer Legal documents, managing staff

### ISSUE THREAD

**Issue by iMohamedSamir** [webkul/hotelcommerce#144]
Hi, How about adding new fields to the internal customer page to register their:
Document Type: Passport, National ID, Driver's licence.
Document Number.
Document Photo.
Also it would be great if one is able to register new member staff to manage/take/register/edit/cancel orders, customers, etc..

**Comment by shreesh-webkul** [comment]
@iMohamedSamir 

Thanks for your suggestion. Currently, we have added only the basic required fields for customers to sign up, We might add additional fields for the customer in the future. 
You can also contribute by raising PR for this feature and help the community. 

If you want us to implement this for you please raise a ticket at https://webkul.uvdesk.com/en/customer/create-ticket/
