### ISSUE TITLE
getHotelCartBookingData: Multiplication to be optimized to simplify support

### ISSUE THREAD

**Issue by wdammak** [webkul/hotelcommerce#153]
modules/blockcart/blockcart.php
modules/hotelreservationsystem/classes/HotelCartBookingData.php

The two functions(getHotelCartBookingData) have almost the same result, so it is better to adapt and keep only one (I think you have to keep the function of the HotelCartBookingData class since it is static by adding a parameter or adapting the blockcart code so that it uses that of HotelCartBookingData::getHotelCartBookingData)

**Comment by shreesh-webkul** [comment]
@wdammak 

Thanks for the suggestion. Yes, we can use HotelCartBookingData::getHotelCartBookingData for blockcart and will update it in the next version.
