### ISSUE TITLE
Error while installation at create shop and languages

### ISSUE THREAD

**Issue by expertsudhir** [webkul/hotelcommerce#18]
Tried several times on my localhost, godaddy both. but always it stops at 23%.
Localhost using XAMPP Control Panel v3.2.2

![hotelcommerce_error](https://cloud.githubusercontent.com/assets/23475399/26521612/24972d94-431f-11e7-9b26-1207d190b2e0.PNG)

**Comment by sumitwebkul** [comment]
Hello,

We recommend you to raise a ticket at https://webkul.uvdesk.com/. We will need your FTP details and backoffice login credentials to check the issue. So Please provide the above required details while raising ticket. We will definitely resolve your issue there ASAP.

Thanks.

**Comment by expertsudhir** [comment]
Thanks Webkul. Finally I got success to install on my local Xampp Server. Issue found is PHP version. Previously I was using PHP 7.1. Now it is perfectly installed on PHP 5.4. 

Now, I am getting issue when uploading on GoDaddy windows hosting server. It is showing 500. Please help to provide any document (if available to you) containing steps to put/upload on any 3rd party hosting server.

**Comment by sumitwebkul** [comment]
Hello,

We recommend you to raise a ticket at https://webkul.uvdesk.com/. We will need your FTP details and backoffice login credentials to check the issue. So Please provide the above required details while raising ticket. We will definitely resolve your issue there ASAP.

Thanks.
