### ISSUE TITLE
Installation issue @ 67%

### ISSUE THREAD

**Issue by XpanxionX** [webkul/hotelcommerce#20]
Having an issue at 67% during installation... Help is much appreciated. Thank you.
Reference
Create settings.inc file
Create database tables
Create default shop and languages
Populate database tables
Configure shop information
Install demonstration data
Install modules
Cannot install module "wktestimonialblock"
An error occurred during installation...
You can use the links on the left column to go back to the previous steps, or restart the installation process by clicking here.
![capture](https://cloud.githubusercontent.com/assets/13964331/26709780/e6436870-4772-11e7-9776-7d7a16c1f5cd.PNG)

**Comment by sumitwebkul** [comment]
Hello,

We recommend you to raise a ticket at https://webkul.uvdesk.com/. We will need your FTP details and backoffice login credentials to check the issue. So Please provide the above required details while raising ticket. We will definitely resolve your issue there ASAP.

Thanks.

**Comment by XpanxionX** [comment]
The problem got resolved. Thank you for your concern webkul. i just changed my php version and it worked fine

**Comment by umarbashirdar** [comment]
@XpanxionX where did you change the php version ?

**Comment by sumitwebkul** [comment]
@umarbashirdar you can also visit https://github.com/webkul/hotelcommerce/issues/41 . It may help you to resolve your issues on installation.

**Comment by umarbashirdar** [comment]
It moved beyond that point. But after installation completes, i click on the "Manage you store" (Back office) and it redirects me to this URL 

http://localhost:8080/hotelcom/admin620ejp6wd/index.php?controller=AdminLogin&token=05fb21ead6fd4c63cfb489c99bb79ba8

It display an empty page.

However, i am able to "View Front office" by clicking on "Discover your store".

To be precise, i am unable to view the admin part, it shows an empty page

**Comment by umarbashirdar** [comment]
@sumitwebkul  Is there any fix to the problem?
