### ISSUE TITLE
PHP 7 support

### ISSUE THREAD

**Issue by seme1** [webkul/hotelcommerce#278]
Is PHP 7 supported ? If not, when will it be ?

**Comment by shreesh-webkul** [comment]
@seme1 
The latest version of QloApps (version 1.5.1) supports PHP from version 5.4 to PHP 7.1
In the next release, PHP support will be from version 5.6 to PHP 7.4

**Comment by wdammak** [comment]
to close

**Comment by shreesh-webkul** [comment]
Closing this issue
The latest QloApps release supports PHP7.
https://github.com/webkul/hotelcommerce/releases/latest
