### ISSUE TITLE
minimum stay nights + Dashboard for monitoring room occupancies

### ISSUE THREAD

**Issue by seme1** [webkul/hotelcommerce#279]
Are the following features implemented in the system yet ? 
minimum stay nights + Dashboard for monitoring room occupancies

**Comment by shreesh-webkul** [comment]
@seme1 
The above features are not implemented till the current release.
We are working on both the features and it is in our roadmap to implement these features in the upcoming release.

**Comment by shreesh-webkul** [comment]
Dashboard for monitoring room occupancies is now implemented in the latest release of QloApps.
[https://github.com/webkul/hotelcommerce/releases/late](https://github.com/webkul/hotelcommerce/releases/latest)

Minimum stay nights feature will be released in the upcoming version of QloApps
