### ISSUE TITLE
add products to order

### ISSUE THREAD

**Issue by Thesee** [webkul/hotelcommerce#33]
Hi, 
is there a way (maybe an hidden way?) to add a product to an order?
eg: my customer booked a room, then I need to add to the order a wine bottle or a breakfast. 
So i have all in one order an one invoice. Is it possible to do?

**Comment by sumitwebkul** [comment]
Hello,

Currently this functionality is not available. We recommend you to create a ticket at https://webkul.uvdesk.com/ and list all your requirements there. We will check your requirements there and uadate you accordingly.
Thanks
