### ISSUE TITLE
Bug increase the number of rooms after click on button (-)

### ISSUE THREAD

**Issue by wdammak** [webkul/hotelcommerce#330]
The number of available rooms does not increase after increasing the number of rooms with click on button (-)

Try to increase then reduce the number of rooms and you will see the bug

**Comment by shreesh-webkul** [comment]
Unable to reproduce this bug.
Please provide us with the PHP and MySQL versions you are running.

**Comment by wdammak** [comment]
@shreesh-webkul : now the calcul Room(s) Left ! dont work after click on button add No. of Rooms(+)
https://demo.qloapps.com/196-179-46-98/the-hotel-prime/3-super-delux-rooms.html
Firefox

**Comment by wdammak** [comment]
also for Subtotal and extras

**Comment by shreesh-webkul** [comment]
@wdammak 
`calcul Room(s) Left !` is working on our end after clicking on the button `add No. of Rooms(+)` on  firefox.
Please provide us with your environment where you are facing this issue 
- firefox version
- operating system.

https://user-images.githubusercontent.com/55269017/166249099-4cfb5040-1686-416c-b7a2-10bad42507dd.mp4

**Comment by wdammak** [comment]
5 Room(s) Left!
? 
not 1 Room(s) Left!
?
Subtotal is OK today

**Comment by shreesh-webkul** [comment]
@wdammak 

"Num" Room(s) Left! only gets updated once you click "Book Now" button, while changing the quantity of room we only update price details.

**Comment by wdammak** [comment]
@shreesh-webkul 
thank you
Will it dynamically update if someone else has booked rooms in the meantime?

**Comment by shreesh-webkul** [comment]
If a room is booked by someone else while you are selecting the room the customer will only be able to buy the remaining quantity of that room.
currently, if the customer clicks on the "+" button and other rooms are booked by some other user the customer will see "Room not available" message, but in the upcoming version the "num room(s) left" text will also be updated.
