### ISSUE TITLE
Cannot Install 

### ISSUE THREAD

**Issue by showermj** [webkul/hotelcommerce#4]
SQL error on query All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead When creating data table

**Comment by sumitwebkul** [comment]
Thanks for contributing in Qlo apps. To make primary key not null Here is the constraints imposed on a field which is to be made primary key  in a table e.g.-  `id` int(11) NOT NULL AUTO_INCREMENT and then we specify this field as primary key like  PRIMARY KEY (`id`) . So Primary key is already Not Null in our tables.

**Comment by devaroop** [comment]
This is an error for latest versions of mysql. Try with mysql 5.5.51 and it should work.
