### ISSUE TITLE
Error while installation at create shop and languages at 23% with the docker image

### ISSUE THREAD

**Issue by gispk47** [webkul/hotelcommerce#40]
i try to change the default language to both en and zh, and always connect to internet when i run the installation,and met this error everytime. the php version in the docker file seems php5,and i can't find the error log on the server,where it should be? thanks

**Comment by sumitwebkul** [comment]
Hello,
As Qloapps is not compatible with php 7.x.x. So please make sure you are not using php version 7.x.x . Use php lower versions like 5.6.x . 
Please make sure curl library also installed on your server.
Visit https://qloapps.com/install-qloapps/ once to set up your environment for the Qloapps installaion.
Please try once after replacing the below files  - 
**hotelcommerce/modules/hotelreservationsystem/classes/HotelBranchInformation.php**
**hotelcommerce/modules/wktestimonialblock/controllers/admin/AdminTestimonialsModuleSettingController.php** 
**hotelcommerce/modules/hotelreservationsystem/classes/HotelImage.php**
From the files we have attached.
Try installing after these changes. In case issue persists then we recommend you to raise a ticket at https://webkul.uvdesk.com/ . We will resolve your issue there.
[installIssue.zip](https://github.com/webkul/hotelcommerce/files/1751537/installIssue.zip)

**Comment by gispk47** [comment]
thanks
i'm using this docker image https://hub.docker.com/r/webkul/qloapps_docker/
php version is 5.5.9,and php-curl is installed in the image too
i replace the three file still got the same error

**Comment by sumitwebkul** [comment]
Hello,
Please raise a ticket at https://webkul.uvdesk.com/ and list your issues there. We will resolve your issue there.
Thanks

**Comment by gispk47** [comment]
seems language zh translate templates got some errors,i used just en to setup it and success

**Comment by sumitwebkul** [comment]
Ok,
We will check this issue and try resolve this issue in the comming upgradations.
Thanks.
