### ISSUE TITLE
Preparation Time for Check-In

### ISSUE THREAD

**Issue by Barbers** [webkul/hotelcommerce#440]
Hi,

for one setup we need a preparation time from 2 days.
Currently it seems that it is not possible to block bookings for the next 2 days.
Every customer can book a room today if at least one is free.

Greetings

**Comment by abhisheksharma906** [comment]
Hi @Barbers , 

The asked feature isn't available in the current QloApps ver 1.5.2. To discuss your specific requirement for "Preparation Time for Check-In" in greater detail, you can raise a ticket at our support ticket system https://webkul.uvdesk.com/en/customer/create-ticket/ or directly mail us at support@qloapps.com.

Thanks,
