### ISSUE TITLE
Latest version available?

### ISSUE THREAD

**Issue by bortek** [webkul/hotelcommerce#446]
Hi

Looks like the codebase has not been updated for months and even years. Docker image in the dockerhub 2 years old.   I wonder if there is a more fresh fork that folks are using preferably with docker compose where one could specify local storage options to be mounted into the container.

Folks what do you use as a recent version?

**Comment by shreesh-webkul** [comment]
@bortek 
The new version of QloApps will be release by the end of this month along with the updated docker image.

You can use the current docker image for the time being, if you are facing any issue while using the current docker image, we suggest you to use the latest release codebase directly or wait till the release of new version.

**Comment by bortek** [comment]
Thats great news. Thanks for the update.
