### ISSUE TITLE
Why did you abolish VAT?

### ISSUE THREAD

**Issue by wdammak** [webkul/hotelcommerce#487]
I noticed that you have removed the VAT, where there are many business customers who want to have invoices with the tax to include it in the accounts of their companies.
I don't understand this choice to no longer display the tax everywhere in the latest commits.
It would have been better to have a choice option in the customer card which allows him to display or not the tax in his invoices.
Anyway when we talk about an invoice it must absolutely display the tax somewhere in the invoice even if in the case of a 0 tax (VAT exemption). Otherwise, we speak of a label as in stores.

**Comment by shreesh-webkul** [comment]
@wdammak 

In the upcomming verion of QloApps, there are updations in the tax process. So some changes are done for the related codes.

The VAT is not abolished in QloApp. We are working on this and this is under development process.

Once we will create a PR for this, we will definitely update you.

Also, any changes in VAT module does not affect (hide/remove) tax in invoice in any way, the invoice will be generated in the same way as before.
