### ISSUE TITLE
Bug: htl_room_type_feature_pricing doesn't exist in db_structure

### ISSUE THREAD

**Issue by wdammak** [webkul/hotelcommerce#488]
Bug: htl_room_type_feature_pricing doesn't exist in db_structure
or delete getWsFeaturePrices function
https://github.com/webkul/hotelcommerce/blob/c8bdac6cdd18b793ed4b10e37506736f444eaa10/classes/Product.php#L6042

**Comment by shreesh-webkul** [comment]
@wdammak 

In the current version 1.5.x and upcoming versions 1.6.x of QloApp, the data structure is defined using 2 files `/install/data/db_structure.sql` and `/modules/hotelreservationsystem/classes/HotelReservationSystemDb.php`.

In future, with the major releases of QloApps (1.7.x), the data structure will be defined using a single file `/install/data/db_structure.sql`.
