### ISSUE TITLE
Bug: hrt.`min_los`, hrt.`max_los` doesn't exist in db_structure

### ISSUE THREAD

**Issue by wdammak** [webkul/hotelcommerce#489]
Bug: hrt.`min_los`, hrt.`max_los` doesn't exist in db_structure

https://github.com/webkul/hotelcommerce/blob/c8bdac6cdd18b793ed4b10e37506736f444eaa10/modules/hotelreservationsystem/classes/HotelRoomType.php#L224

**Comment by shreesh-webkul** [comment]
@wdammak 

In the current version 1.5.x and upcoming versions 1.6.x of QloApp, the data structure is defined using 2 files `/install/data/db_structure.sql` and `/modules/hotelreservationsystem/classes/HotelReservationSystemDb.php`.

In future, with the major releases of QloApps (1.7.x), the data structure will be defined using a single file `/install/data/db_structure.sql`.
