### ISSUE TITLE
Failure during installation

### ISSUE THREAD

**Issue by alejandro-uliski** [webkul/hotelcommerce#49]
Hi,
I've tried installing the hotelcommerce1.1.1 several time and I face the same faiure during "Create default shop and languages" on 23% of the installation.

when going back to "system configuration" phase of the installation and retrying the connection to the database the following message appears: "At least one table with same prefix was already found, please change your prefix or drop your database".

I've tried all solutions suggested in prestaShop support such as droping tables, drop the entire db and create new one. I even created a new hosting instance, uploaded the latest hotelcommerce version and reinstalled but I keep facing the same issue. 
any idea?

**Comment by sumitwebkul** [comment]
Hello,
It looks like issue of your environment set up for Qloapps. We recommend you to please visit https://qloapps.com/install-qloapps/ and set up your environement for Qloapps installation.
Please try to install Qloapps after setting up environement as per explained in the blog.
In case issue persists the please create a ticket at https://webkul.uvdesk.com .

Thanks

**Comment by webkul** [comment]
issue is resolved
