### ISSUE TITLE
Bug with the new implementation of use the id_country

### ISSUE THREAD

**Issue by wdammak** [webkul/hotelcommerce#498]
https://github.com/webkul/hotelcommerce/blob/c8bdac6cdd18b793ed4b10e37506736f444eaa10/classes/Product.php#L2360-L2362

in case:

Cart Object
(
    [id] => 
    [id_shop_group] => 1
    [id_shop] => 1
    [id_address_delivery] => 0
    [id_address_invoice] => 0
    [id_currency] => 1
    [id_customer] => 
    [id_guest] => 101
    [id_lang] => 1
    [recyclable] => 0
    [gift] => 0
    [gift_message] => 
    [mobile_theme] => 
    [date_add] => 
    [secure_key] => 
    [id_carrier] => 0
    [date_upd] => 
    [checkedTos] => 
    [pictures] => 
    [textFields] => 
    [delivery_option] => 
    [allow_seperated_package] => 
    [is_advance_payment] => 
    [_products:protected] => 
    [_taxCalculationMethod:protected] => 0

This will cause an error:
Notice: Trying to access array offset on value of type bool in \www\hotelcommerce\classes\Product.php on line 2362

This is the case where a customer visits the site for the first time and his cart is empty

**Comment by shreesh-webkul** [comment]
@wdammak 

We have checked and found this error does exists, We will resolve this in future updates.


Thanks for your contributions.

**Comment by shreesh-webkul** [comment]
Similar issue resolution : #397

**Comment by wdammak** [comment]
@shreesh-webkul 
i thank also you must change the getCountryAndState function:
```

public static function getCountryAndState($id_address)
    {
        if (isset(self::$_idCountries[$id_address])) {
            return self::$_idCountries[$id_address];
        }
        if ($id_address) {
            $result = Db::getInstance(_PS_USE_SQL_SLAVE_)->getRow('
			SELECT `id_country`, `id_state`, `vat_number`, `postcode` FROM `'._DB_PREFIX_.'address`
			WHERE `id_address` = '.(int)$id_address);
        } else {
            $result = false;
        }
        self::$_idCountries[$id_address] = $result;
        return $result;
    }

```
**change**
```
  } else {
            $result = false;
        }
```
**by**
```
 } else {
            $result = array();
        }

```
return empty array and not false because the expected result is an array
This will avoid warnings of access to an array of a variable of type **false** => warning

**Comment by wdammak** [comment]
An example where using false causes a warning of the current Product class code

https://github.com/webkul/hotelcommerce/blob/c8bdac6cdd18b793ed4b10e37506736f444eaa10/classes/Product.php#L2837-L2847

here it will cause warning if the getCountryAndState function returned false. (if ($address_infos['id_country']) {)

**Comment by shreesh-webkul** [comment]
> @shreesh-webkul i thank also you must change the getCountryAndState function:
> 
> ```
> 
> public static function getCountryAndState($id_address)
>     {
>         if (isset(self::$_idCountries[$id_address])) {
>             return self::$_idCountries[$id_address];
>         }
>         if ($id_address) {
>             $result = Db::getInstance(_PS_USE_SQL_SLAVE_)->getRow('
> 			SELECT `id_country`, `id_state`, `vat_number`, `postcode` FROM `'._DB_PREFIX_.'address`
> 			WHERE `id_address` = '.(int)$id_address);
>         } else {
>             $result = false;
>         }
>         self::$_idCountries[$id_address] = $result;
>         return $result;
>     }
> ```
> 
> **change**
> 
> ```
>   } else {
>             $result = false;
>         }
> ```
> 
> **by**
> 
> ```
>  } else {
>             $result = array();
>         }
> ```
> 
> return empty array and not false because the expected result is an array This will avoid warnings of access to an array of a variable of type **false** => warning

In function `getCountryAndState` the return can be false if id_address is passed but does not exists because `getRow` function return false if result is not found.
``` php
 $result = Db::getInstance(_PS_USE_SQL_SLAVE_)->getRow('
			SELECT `id_country`, `id_state`, `vat_number`, `postcode` FROM `'._DB_PREFIX_.'address`
			WHERE `id_address` = '.(int)$id_address);
```

so if we update the suggested code will still need to check for two possible return values.

Also the empty array still does not resolve the issue in the below example as the index `id_country` will still be undefined in empty array.
https://github.com/webkul/hotelcommerce/blob/c8bdac6cdd18b793ed4b10e37506736f444eaa10/classes/Product.php#L2837-L2847

instead we can do
``` php
if (isset($address_infos['id_country']) && $address_infos['id_country']) { 
     $id_country = (int)$address_infos['id_country']; 
     $id_state = (int)$address_infos['id_state']; 
     $zipcode = $address_infos['postcode']; 
 } 
```
