### ISSUE TITLE
PHP 7 support

### ISSUE THREAD

**Issue by Cat5TV** [webkul/hotelcommerce#50]
I'm very keen to try hotelcommerce, but disappointed to see it does not support PHP 7.

PHP 5.6 (which you recommend) ended its support life almost 1.5 years ago, and security fixes for it will also be ending in just a few months.

Our hosting does not allow anything less than PHP 7.2.

Any update on when PHP 7 will be supported?

Thanks so much!  Looks like great work and I can't wait to use it.

**Comment by sumitwebkul** [comment]
We are working on PHP 7 support for Qloapps and very soon we will release the version supports PHP 7 .
But you can install it on lower version now and go through the functionalities of system.
Thanks.

**Comment by webkul** [comment]
We have launched new version 1.3.0 , 1.3.0 fully supports PHP7
