### ISSUE TITLE
34 error

### ISSUE THREAD

**Issue by Nyx311** [webkul/hotelcommerce#533]
![image](https://user-images.githubusercontent.com/38715372/218987866-0112f23a-1ed0-424e-a64e-91dd31703861.png)
php 5.6.9  mysql 5.5.29

**Comment by abhishek-webkul** [comment]
@yinyutaoyyt 

Thanks for reporting this issue!

We will be soon providing a patch to fix this issue.

**Comment by Nyx311** [comment]
thanks
