### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by itsalimanuel** [webkul/hotelcommerce#60]
> domain.com redirected you too many times.
> Try clearing your cookies.
> ERR_TOO_MANY_REDIRECTS

where the problem here?

**Comment by bitcoinbrisbane** [comment]
Sometimes with PHP that can happen if the site is forcing SSL and you dont have a cert.

**Comment by itsalimanuel** [comment]
no, I have SSL and it's working

**Comment by itsalimanuel** [comment]
@bitcoinbrisbane no, I have SSL and it's working

**Comment by sumitwebkul** [comment]
@itsalimanuel 
Are you still facing this issue?
If yes, we request you to please share your FTP details and admin login credentials at https://webkul.uvdesk.com . We will check the issue on your server itself.

**Comment by itsalimanuel** [comment]
@sumitwebkul okay i will

**Comment by sumitwebkul** [comment]
@itsalimanuel 
Thanks for understanding. We will check the issue at https://webkul.uvdesk.com

**Comment by computersalat** [comment]
@sumitwebkul 
I still can't understand why there is still SSL handling _inside_ the app.
It is the duty of the webserver and not of the application.
You should either get rid of that code or fixing it not to do a rewrite to `http` while the webserver is already doing `https` for the whole site ...

**Comment by sumitwebkul** [comment]
We have to make some rules in  .htacces file for the SSL settings in QloApps under Preferences -> General tab. So this setting is there in the QloApps.

Also, till now no issues is created regarding this setting by users.

Some times user raises only if they enable ssl certificate on their domain but forget to enable ssl setting on QloApps backoffice.

To enable SSL on QloApps site, follow below steps in the Back-office- 
- Go to Preferences -> General
- Click Please click here to check if your shop supports HTTPS in Enable SSL field
- Enable SSL to Yes
- Enable SSL on all pages to Yes
- Save the settings.

**Comment by computersalat** [comment]
YOU didn't get the point.
When the webserver is providing SSL for the _whole_ website already it is _nonsense_ to do a _rewrite_ to _http_
A simple check for `${HTTPS}` would make the _mentioned_ switches obsolete.
Improve your code and get rid of that _antique_ opinion that the _application_ should handle `SSL`.

**Comment by sumitwebkul** [comment]
@computersalat 
Thanks for your suggestion. 
We will look into this and add this suggestion to our future road map if needed.

**Comment by computersalat** [comment]
@sumitwebkul 
IMHO it is needed ...
