### ISSUE TITLE
[BUG] Null quantity when you click at Book Now

### ISSUE THREAD

**Issue by wdammak** [webkul/hotelcommerce#66]
https://demo.qloapps.com/home/11-super-delux-rooms.html

Null quantity when you click at Book Now

**Comment by sumitwebkul** [comment]
@wdammak 
Our demo gets reset every day. So we can not check the issue right now on the demo. Can you please tell us the exact condition when this issue occurred?

**Comment by wdammak** [comment]
@sumitwebkul thx! fixed
