### ISSUE TITLE
Installation failure - create database tables

### ISSUE THREAD

**Issue by nadilas** [webkul/hotelcommerce#69]
Hello there,

I can't find any detailed logs why, the installation stops at 12% while creating database tables. Many tables are created then the script simply fails with any error log output.

<img width="703" alt="Screenshot 2019-06-19 at 23 40 59" src="https://user-images.githubusercontent.com/5324856/59803525-024c4200-92ec-11e9-9a8f-13a9f0be2002.png">

MySQL Version is: 5.6
Php Version is: 5.6

**Comment by sumitwebkul** [comment]
Hello,
We have to check the issue on your server.
please raise a ticket at https://webkul.uvdesk.com/ with the FTP details and domain link on which you are installing QloAPps. 
We will resolve your issue there.
Thanks

**Comment by nadilas** [comment]
Thanks @sumitwebkul. The setup is running behind a kubernetes cluster. Which files are you interested in? Let me upload them.

**Comment by sumitwebkul** [comment]
@nadilas 

We request you to please once replace the attached file (after extracting zip file) with the file at below path -

**hotelcommerce/install/data/db_structure.sql**

After replacing the file try to install QloApps Again.

In case if the issue still persists then please provide us with the error log of the server.

[db_sql.zip](https://github.com/webkul/hotelcommerce/files/3313270/db_sql.zip)

**Comment by wdammak** [comment]
to close
