### ISSUE TITLE
link to admin demo

### ISSUE THREAD

**Issue by wdammak** [webkul/hotelcommerce#718]

**Comment by abhishek-webkul** [comment]
You can access Back office (admin) of the demo hosted at https://demo.qloapps.com/ by clicking on '**Explore Back Office**' button shown in footer on all front office pages of the demo.

![Access Back Office](https://user-images.githubusercontent.com/84142535/234767635-bd76d5fd-4092-401a-82c4-e018fcf46e2d.jpeg)

**Comment by wdammak** [comment]
can you add it in documentation?
