### ISSUE TITLE
disable hotel chain

### ISSUE THREAD

**Issue by n3ssi3** [webkul/hotelcommerce#8]
Hey there

Just a quick question,
I am only having 1 hotel, so it does not make sense to actually show hotel location and hotel selection in the search form. 
Do you already have a setting to disable it?
Or would you accept pull requests that would check if there is more than 1 hotel and show the form accordingly?

Thanks for the work you did

Cheers
Nessie

**Comment by sumitwebkul** [comment]
Hello,
Thanks for using Qloapps. Yes, There is an option provided through which you can hide the location option on your site. Just follow few following steps  -
-Visit Hotel Reservation System -> Settings Tab. 
-Then select "Hotel General Configuration" option among the various settings.
-On Hotel General Configuration Settings page disable the option "Enable Hotel Location".
Please visit the links below to see the screenshots for more information.
http://awesomescreenshot.com/04b66tim38
http://awesomescreenshot.com/04d66tinca
For any further query please let us know.
Thanks.

**Comment by n3ssi3** [comment]
thanks :)
