### ISSUE TITLE
OnDemand select list with multi-choices

### ISSUE THREAD

**Issue by wdammak** [webkul/hotelcommerce#87]
For a OnDemand feature, we can offer a selection list and the user can check two or three options in this list.

**Comment by sumitwebkul** [comment]
@wdammak 
We are not very clear about your suggestion.
But it looks you are asking about **Additional Facilities** feature which is already implemented with QloApps.
I suggest you to once visit https://qloapps.com/qlo-reservation-system/#section-9 and read in details about **Additional Facilities** feature.
In case of any doubt please let me know.

**Comment by wdammak** [comment]
@sumitwebkul
for example I have an ADDITIONAL FACILITIES with 3 options (option1 = $ 100, option2 = $ 150, option3 = $ 200)
The customer can add just one option or multiple options
If it ticks option1 + option3 => price 100 + 200 = $ 300
This saves you from creating multiple select to suggest all possible cases
attached photo for more explanation

![image](https://user-images.githubusercontent.com/26695620/69686556-6c012100-10c0-11ea-9411-8ce786f442dd.png)
https://mdbootstrap.com/docs/jquery/forms/multiselect/

**Comment by sumitwebkul** [comment]
@wdammak 

Let me explain you the thoughts behind the creations of additional facilities.

Admin can provide user to choose additional facilities in two ways - 

**Case 1 -** Customer can choose multiple facilities by selecting multiple check-boxes. For this admin will have to create additional facilities separately (without advance options). 
https://prnt.sc/q2mr4z
https://prnt.sc/q2n4xj

**Case 2 -** Customer can choose only one facility option among admin's provided multiple options (with different prices). 
For this admin will have to create additional facilities with advance options. And at the front end, customer will choose one among multiple provided options. in this case customer will select one option in the select field.
https://prnt.sc/q2mrae
https://prnt.sc/q2mu10

For your case, 
**## This saves you from creating multiple select to suggest all possible cases**
Currently, admin has to create multiple facilities using Case 1 and customer will be able to choose multiple options by the check-boxes.
However, We appreciate your suggestion and we definitely take it into consideration for improving this functionality in future.

**Comment by wdammak** [comment]
@sumitwebkul dear! any news?

**Comment by sumitwebkul** [comment]
@wdammak 

Regarding above suggestion, we have not changed in the QloApps yet.

Although there are  new features added in the Additional facilities in the latest released version 1.4.1
- Additional facilities functionality is added at the back-office order creation process.
- Add tax on the additional facility.
- Charge on per day basis of the additional facility.

Please visit https://github.com/webkul/hotelcommerce/blob/v1.4.x/CHANGELOG.txt for the Change log of the latest version.

Thanks

**Comment by wdammak** [comment]
we wait 1.4.2 :)

**Comment by sumitwebkul** [comment]
Ok Thanks

**Comment by sumitwebkul** [comment]
@wdammak 

It's not necessary that all the suggestions will be implemented in the system.
We take suggestions from the contributors and users and try to implement them as per the feasibility and importance.
We gather data from different sources to improve the system.
Suggestions may be modified or rejected or delayed as per the global system need.

Thanks

**Comment by wdammak** [comment]
https://github.com/davidstutz/bootstrap-multiselect
http://davidstutz.de/bootstrap-multiselect/
