### ISSUE TITLE
Can I deploy to Heroku?

### ISSUE THREAD

**Issue by parmalatinter** [webkul/hotelcommerce#88]
I tried to deploy app to Heroku.
But could not work fine.
First deploy : work fine
Second deploy : not work fine, redirect to Installation Assistant 
Maybe deleted  any foloder and file that made by first deploy.

Can you support heroku?

*I changed following for heroku deploy, and renamed intall folder to install1 when after first deploy.
https://github.com/webkul/hotelcommerce/compare/v1.4.x...parmalatinter:v1.4.x

**Comment by sumitwebkul** [comment]
@parmalatinter 
## Can you support Heroku?
There should be no problem with the deployment.
But give me some time to look into it.

**Comment by sumitwebkul** [comment]
@parmalatinter 

Please let me know in the second deployment, 
whether are you trying to install a fresh copy of QloApps folder?
Or
are you trying to install the same folder which is installed once? 

Please make sure to install a fresh copy of QloApps every time.

**Comment by parmalatinter** [comment]
Thank you for your reply.
I am trying ' install the same folder which is installed once'.
but I want to do first one,   fresh copy is better.

heroku develop needs:
Unable to save local file, therefore it needs commit before host server changes files.

Now working after following step
```
add composer and composer.lock, composer.json
add .user.ini
add /config/settings.inc.php * is made by the localhost app after Installation Assistant
renamed intall folder
rename cache folder to 'tmp'
````


- Commits history of above steps

commit 5179b7141a8df12aae175a54b41f76cae9d9acc5
Author: parmalatinter <parmalatinter@gmail.com>
Date:   Fri Dec 6 18:20:49 2019 +0900

    change db structure for heroku

commit 0c5625fa0936a0adb9b43fc199b3ff29f4bfba47
Author: parmalatinter <parmalatinter@gmail.com>
Date:   Fri Dec 6 17:11:38 2019 +0900

    add composer

commit 4474a6656832751b12da3a1d8c488527216ade1d
Author: Yosuke Kobayashi <parmalatinter@gmail.com>
Date:   Fri Dec 6 16:50:05 2019 +0900

    Update composer.lock

commit bbbc4fbe379b833f7d3116d0284e974485d4362a
Author: Yosuke Kobayashi <parmalatinter@gmail.com>
Date:   Fri Dec 6 16:49:20 2019 +0900

    Update composer.lock

commit e945edc95d68d49a91b4a0fad850fe5038588977
Author: Yosuke Kobayashi <parmalatinter@gmail.com>
Date:   Fri Dec 6 16:46:23 2019 +0900

    Create composer.lock

commit a3b9bcbd9f00677e55a9432e258e33db0b0e255d
Author: Yosuke Kobayashi <parmalatinter@gmail.com>
Date:   Fri Dec 6 16:45:36 2019 +0900

    fix json syntax

commit 2a00f9d2b50b8a69f5d7b81d98ac7d9c86cb95b5
Author: Yosuke Kobayashi <parmalatinter@gmail.com>
Date:   Fri Dec 6 16:39:59 2019 +0900

    for run on heroku

commit 92e5ca50742f030faa476d630c0cc398c46d29bc
Author: Yosuke Kobayashi <parmalatinter@gmail.com>
Date:   Fri Dec 6 16:37:02 2019 +0900

    for run on heroku

commit c632927a07fb8f836361a402ea68b70976a72b31
Author: Yosuke Kobayashi <parmalatinter@gmail.com>
Date:   Fri Dec 6 16:26:16 2019 +0900

    Update .user.ini

commit 0ef64e6d9c5272fc23f41d5bfcfed2cd9a5457ed
Author: Yosuke Kobayashi <parmalatinter@gmail.com>
Date:   Fri Dec 6 16:24:06 2019 +0900

    add php ini update file for heroku

**Comment by parmalatinter** [comment]
But now issue is exist only run on heroku. 
Now working but not perfect.

https://github.com/parmalatinter/hotelcommerce/wiki/Bug-form-button-open-error-page

**Comment by sumitwebkul** [comment]
We are not clear about your issue.
We request you to please explain the issue in more detail with the help of screenshots.

**Comment by parmalatinter** [comment]
Sorry, I rewrote issue detail.

- bug step

1. I add new hotel in admin page.
2. Search hotel that added hotel and go to booking page
![hotel-sample herokuapp com_index php (1)](https://user-images.githubusercontent.com/6459902/70507468-c3e36180-1b6f-11ea-9b25-1c3807cc89a9.png)

3. Push Search button
![hotel-sample herokuapp com_index php_controller=category id_lang=1 date_from=2019-12-10 date_to=2019-12-11](https://user-images.githubusercontent.com/6459902/70507500-d362aa80-1b6f-11ea-8633-98fdea8a1d66.png)

4. Show error
![chrome-error___chromewebdata_](https://user-images.githubusercontent.com/6459902/70507519-dd84a900-1b6f-11ea-8eb1-5b40719c606a.png)

* but reload page to show fine
![hotel-sample herokuapp com_index php_controller=category id_lang=1 date_from=2019-12-11 date_to=2019-12-12](https://user-images.githubusercontent.com/6459902/70507565-f8efb400-1b6f-11ea-991a-d8c5ccab545f.png)

**Comment by sumitwebkul** [comment]
@parmalatinter 
I have to check the issue by reproducing it on your QloApps website.
So I request you to create a ticket at https://webkul.uvdesk.com/en/customer/create-ticket/ and provide us with your FTP details and Admin Url and login credentials.
Thanks

**Comment by parmalatinter** [comment]
A new ticket #141065 has been generated.
Please refer it.

**Comment by sumitwebkul** [comment]
Ok @parmalatinter ,
We will check your issue and update you on the same ticket.
Thanks.
