### ISSUE TITLE
When will the future release be published

### ISSUE THREAD

**Issue by wdammak** [webkul/hotelcommerce#89]
I noticed that you opted for batch and local development, if the modifications will be with partial PR it will be more collaborative and it will insist a lot of developers to participate!
it remains only a personal opinion
Otherwise do you have an approximate date for the future release?
Bests

**Comment by sumitwebkul** [comment]
**I noticed that you opted for batch and local development, if the modifications will be with partial PR it will be more collaborative and it will insist a lot of developers to participate**
- Can you explain more, What exactly you mean for partial PR?

**Do you have an approximate date for the future release?**
- Yes, we are very close to the next release and it will be released soon (approximately within 2-3 weeks).

**Comment by wdammak** [comment]
-  Can you explain more, What exactly you mean for partial PR?

Post PR every time there has been a code change instead of posting all the new features all of a sudden.

**Comment by sumitwebkul** [comment]
@wdammak 
Thanks for your continuous suggestions.
And we will soon start this process in the QloApps releases.

**Comment by wdammak** [comment]
@sumitwebkul 
we are waiting for good news!
:+1:
