### ISSUE TITLE
Questions on overrides

### ISSUE THREAD

**Issue by fbaldo31** [webkul/hotelcommerce#899]
Hello and bravo for the work done !
I saw a duplicated class which seems to exactly the same code`RoomTypeServiceProduct`

1. `modules/hotelreservationsystem/classes/RoomTypeServiceProduct.php`
2. `themes/hotel-reservation-theme/modules/hotelreservationsystem/class/RoomTypeServiceProduct.php`

So my first question is there is any reason to do it or more something like 'forgotten' ?
My other question is where is the best place to override it as I am using the default theme ?
1. `modules/mymodule/override/modules/hotelreservationsystem/classes/RoomTypeServiceProduct.php`
2. `modules/mymodule/themes/hotel-reservation-theme/modules/hotelreservationsystem/class/RoomTypeServiceProduct.php`

I am a bit lost with this particular case, specially because I am not aware of future updates.
I am using last version.

**Comment by shreesh-webkul** [comment]
> Hello and bravo for the work done ! I saw a duplicated class which seems to exactly the same code`RoomTypeServiceProduct`
> 
> 1. `modules/hotelreservationsystem/classes/RoomTypeServiceProduct.php`
> 2. `themes/hotel-reservation-theme/modules/hotelreservationsystem/class/RoomTypeServiceProduct.php`
> 
> So my first question is there is any reason to do it or more something like 'forgotten' ?

The file you pointed out does not exist in the default system, It seems like you have placed this file. https://github.com/webkul/hotelcommerce/tree/v1.6.0/themes/hotel-reservation-theme/modules



> My other question is where is the best place to override it as I am using the default theme ?
> 
> 1. `modules/mymodule/override/modules/hotelreservationsystem/classes/RoomTypeServiceProduct.php`
> 2. `modules/mymodule/themes/hotel-reservation-theme/modules/hotelreservationsystem/class/RoomTypeServiceProduct.php`
> 
> I am a bit lost with this particular case, specially because I am not aware of future updates. I am using last version.

In the Current version of QloApps only the "Core classes" and "Module main classes" can be overridden. In the upcoming version, you will be able to override "Module controllers" but overriding module classes in not available in QloApps.

Please let us know what you want to achieve so that we can suggest you a solution.

**Comment by fbaldo31** [comment]
First you are right it seems I created `themes/hotel-reservation-theme/modules/hotelreservationsystem/class/RoomTypeServiceProduct.php` in first try I guess.

Thanks for explanations, I think it is much more clear for me, and maybe I do not need to override any class.

My need is to create a module in order be able to make a ServceProduct mode price calculation by occupant.
To do so my guess is to have:
- a new table storing this information
- a new admin controller to enable / disable this feature on service products - room type link 
(nice to have would be to reuse service product admin controller but not possible in the current version) 
- an action controller (or several) to apply the calculation rule each time it is needed

**Comment by sumitwebkul** [comment]
@fbaldo31 
Thanks for the information.

Here is some points how you can acheive your requirement as asked by you:

- As currently we do not provide price as per occupancy. So you may need a table for saving opccupancy wise prices settings.

- You can give configuration if price will work on occupancy or not in the service products or in the room type for all service product of room type.
And you can do this with the existing controllers of Service Product and room type.

- You can create settings to set occupancy wise prices as per your requirement in the price section of Service product. You can do this with the existing controller of Service Product.

- Also, you may have to change the business logics on the Classe and different /pages/controllers in front end(where service product price is calculated) for implementing this occupacny wise price.

Hope it will be helpfull.

**Comment by fbaldo31** [comment]
Thanks @sumitwebkul  to raised need to look into frontend classes/controllers, I was missing this part !

-> Indeed using `addServiceProductInCart` method of `RoomTypeServiceProductCartDetail` does the job perfectly : it works like a charm :smile: 

Thanks again
