### ISSUE TITLE
on demand room price

### ISSUE THREAD

**Issue by dikac** [webkul/hotelcommerce#96]
is it possible to input price dynamically when admin create order? or is there any plugin for it?

**Comment by faizansari-bd** [comment]
Hi @dikac 
I think you mean that when the admin is creating order from backend then he should have the option to enter the price of the room type at run time. 
If yes, then no, QloApps does not have any features like that. 

In QloApps we have predefined rates of a room type. We have a dynamic pricing feature by the name of the feature price rule. This feature will as allow you to increase or decrease the prices in specific date ranges,dates and days.

If you want this feature created for you please raise a ticket at https://webkul.uvdesk.com/en/customer/create-ticket/
