### ISSUE TITLE
Admin Folder Name Change Automatically

### ISSUE THREAD

**Issue by robbytriadi** [webkul/hotelcommerce#98]
Hi Qloapps Team,

Please help. How to fix admin name folder change. If I go to admin site, the folder change. This is the capture of URL:

![image](https://user-images.githubusercontent.com/49820621/77405756-3a863100-6de6-11ea-8a79-f0be6a74a38c.png)

Before it happened, I've change folder name to "admin".

Thank you

**Comment by sumitwebkul** [comment]
@robbytriadi 

If you set the name of the admin folder as '**admin**' then on loading the admin URL it will change the folder name every time.
So please set a name of the folder other than **admin** 
like **adminHotel** or anything other than exactly **admin**.

Hope you understand.

Thanks

**Comment by robbytriadi** [comment]
@sumitwebkul it's works.
Thank you for your support
